import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";

const jakartaSans = Plus_Jakarta_Sans({
  subsets: ['latin'], // Opção de subset conforme necessidade
  weight: ['200', '400', '500', '600', '700', '800'], // Pode definir os pesos que precisa
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jakartaSans.className} antialiased text-[#F5F5F5]`}
      >
        {children}
      </body>
    </html>
  );
}
